### ISSUE TITLE
Doesn't compile with Elixir 1.16

### ISSUE THREAD

**Issue by mmower** [jonnystorm/ordered-map-elixir#6]
Trying to compile `OrderedMap` today and came across this error:

== Compilation error in file lib/ordered_map.ex ==
** (CondClauseError) no cond clause evaluated to a truthy value
    expanding macro: OrderedMap.Utility.slice_list_fun/2
    lib/ordered_map.ex:526: Enumerable.OrderedMap.slice/1

**Comment by jonnystorm** [comment]
Hi, @mmower. Thanks for contributing!

FYI: You can read more about the `{protocol}.{impl}` syntax in the [Protocol docs on reflection](https://hexdocs.pm/elixir/1.16.1/Protocol.html#module-reflection). Also, see 11642aa for the rationale around the `slice_list_fun/2` macro.

Basically, the macro was added to insulate us from the last breaking change to `Enumerable.List.slice`. It seems another [breaking change](https://github.com/elixir-lang/elixir/commit/abbc5916faa2bcacd9d44f824cde90dc0fd63045#diff-9a538f965f1fdc2cf9780b1008560f05bfa2ff80d145445abe37a0d70d3828a2L4538-L4540) was introduced in Elixir v1.14.

I'll take a closer look as soon as time allows, but if you get to it before I do, you're welcome to send a pull, as well.

**Comment by jonnystorm** [comment]
@mmower I believe this has been adequately addressed by c900b82 (tagged ~~v0.0.7~~ v0.0.8). Please let me know if you continue to have trouble!

**Comment by mmower** [comment]
Hey, Johnny, thank you for this. I wasn't sure if you'd want to come back to a library after so much time and was trying to grok what it was doing to fix it myself but you beat me to it — that's brilliant. Thank you again. I'm testing v0.0.8 now and will let you know.

**Comment by jonnystorm** [comment]
Closing this, for now, @mmower. Let me know if you still have trouble, and we can reopen.

Thanks, again, for contributing!
